---
- name: Install required software
  become: True
  apt:
    name:
      - python3
      - python3-pip
      - chromium-chromedriver
    state: present

- name: Create asvz-bot user
  become: True
  user:
    name: asvz-bot
    shell: /bin/bash
    state: present

- name: Copy requirements
  become: True
  copy:
    src: requirements.txt
    dest: /home/asvz-bot/requirements.txt
    owner: asvz-bot
    group: asvz-bot

- name: Install required dependencies
  become_user: asvz-bot
  shell: "pip3 install -r /home/asvz-bot/requirements.txt"

- name: Copy script
  become: True
  copy:
    src: asvz_bot.py
    dest: /home/asvz-bot/asvz_bot.py
    owner: asvz-bot
    group: asvz-bot

- name: Remove crontab of asvz-bot
  become: True
  become_user: asvz-bot
  shell: crontab -r

- name: Create cronjob
  become: True
  cron:
    name: "sign up for {{ item.weekday }} at {{ item.hour }}:{{ item.minute }}"
    user: asvz-bot
    minute: "{{ item.minute }}"
    hour: "{{ (item.hour|int - 1) % 24 }}"
    weekday: "{{ (item.weekday|int - 1) % 6 }}"
    job: "/usr/bin/python3 /home/asvz-bot/asvz_bot.py -u {{ username }} -p {{ vault_user_password }} -w {{ item.weekday }} -t {{ item.hour }}:{{ item.minute }} -f '{{ item.facility }}' '{{ item.sportfahrplan }}' >> /home/asvz-bot/cron.log"
  loop: "{{ subscription_times }}"

- name: Keep alive
  become: True
  cron:
    name: "send ping to gateway to keep the pi reachable"
    user: asvz-bot
    minute: "*/2"
    job: "/usr/bin/ping -q -W 1 -c 1 192.168.0.1 > /dev/null"
